# Generated by Django 4.0.2 on 2022-04-12 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('easysurfCommunityIssues', '0003_issue_assignee_issue_resolved_alter_issue_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_resolver', to=settings.AUTH_USER_MODEL),
        ),
    ]
