# Generated by Django 4.0.2 on 2022-03-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easysurfClubs', '0001_initial'),
        ('account', '0004_alter_account_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easysurfClubs.club'),
        ),
    ]
