# Generated by Django 4.0.2 on 2022-04-12 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_personal_info', models.BooleanField(default=False)),
                ('orientation', models.BooleanField(default=False)),
                ('completed_survey', models.BooleanField(default=False)),
                ('joined_club', models.BooleanField(default=False)),
                ('voted_issue', models.BooleanField(default=False)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
