# Generated by Django 4.0.2 on 2022-04-04 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_due', models.DateTimeField(blank=True, default=0, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
