# Generated by Django 4.0.2 on 2022-04-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easysurfFees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_due',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
