# Generated by Django 4.0.2 on 2022-04-11 02:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('easysurfQuestionnaire', '0002_answer_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='surveyees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
