# Generated by Django 4.0.2 on 2022-04-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easysurfHome', '0002_orientationresidentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_portrait',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
