# Generated by Django 4.0.2 on 2022-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easysurfHome', '0003_visitor_visitor_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_relationship',
            field=models.CharField(choices=[('SO', 'Son'), ('DA', 'Daughter'), ('GS', 'Grandson'), ('GD', 'Granddaughter'), ('BR', 'Brother'), ('SI', 'Sister')], default='SO', max_length=2),
        ),
    ]
