# Generated by Django 4.0.2 on 2022-04-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=50)),
                ('meet_times', models.CharField(max_length=50)),
                ('club_portrait', models.ImageField(default=None, null=True, upload_to='images/')),
                ('members', models.IntegerField(default=0)),
            ],
        ),
    ]
