# Generated by Django 4.0.2 on 2022-04-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easysurfClubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='location',
            field=models.CharField(default='Plaza', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='meet_times',
            field=models.CharField(default='Tuesday', max_length=50),
            preserve_default=False,
        ),
    ]
