# Generated by Django 4.0.2 on 2022-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easysurfClubs', '0002_club_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_portrait',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
