# Generated by Django 4.0.2 on 2022-04-04 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('easysurfEvents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='event_subbers', to=settings.AUTH_USER_MODEL),
        ),
    ]
