# Generated by Django 4.0.2 on 2022-04-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easysurfEvents', '0002_alter_event_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
